package com.masaischool.entity;

import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;

/**
 * Service Provider Table:
   - Stores information about registered service providers.
   - Columns: provider_id (Primary Key), provider_name, username, password, working_hours, service_descriptions, and other relevant provider details.
 */

/**
 * @Entity: This annotation is used to mark the class as a JPA entity, which means it will be mapped to a database table.
 * @author 91736
 *
 */
@Entity
public class ServiceProvider {
	/**
	 * @Id: This annotation marks the primary key field of the entity. In this case, providerId is the primary key of the ServiceProvider entity.
	 */
	
	/**
	 * @GeneratedValue: This annotation specifies the strategy for generating the primary key values. In this case, GenerationType.IDENTITY means that the primary key values will be automatically generated by the underlying database.
	 */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "provider_id")
    private Long providerId;

    /**
     * @Column: This annotation is used to specify details about the database column corresponding to the field.
     */
    @Column(name = "provider_name", nullable = false, length = 100)
    private String providerName;
    
    @Column(nullable = false, unique = true, length = 50)
    private String username;
    
    @Column(nullable = false, length = 50)
    private String password;
    
    @Column(name = "working_hour", nullable = false, length = 50)
    private String workingHours;
    
    @Column(name = "service_Description", nullable = false, length = 200)
    private String serviceDescriptions;

    @OneToMany(mappedBy = "serviceProvider", cascade = CascadeType.ALL)
    private List<Appointment> appointments;
    
    @OneToMany(mappedBy = "serviceProvider", cascade = CascadeType.ALL)
    private List<ServiceDetails> serviceDetailsList;

	public ServiceProvider() {
		super();
		// TODO Auto-generated constructor stub
	}

	public ServiceProvider(String providerName, String username, String password, String workingHours,
			String serviceDescriptions, List<Appointment> appointments, List<ServiceDetails> serviceDetailsList) {
		super();
		this.providerName = providerName;
		this.username = username;
		this.password = password;
		this.workingHours = workingHours;
		this.serviceDescriptions = serviceDescriptions;
		this.appointments = appointments;
		this.serviceDetailsList = serviceDetailsList;
	}
	
    // Getters, setters, and other methods

	public Long getProviderId() {
		return providerId;
	}

	public String getProviderName() {
		return providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getWorkingHours() {
		return workingHours;
	}

	public void setWorkingHours(String workingHours) {
		this.workingHours = workingHours;
	}

	public String getServiceDescriptions() {
		return serviceDescriptions;
	}

	public void setServiceDescriptions(String serviceDescriptions) {
		this.serviceDescriptions = serviceDescriptions;
	}

	public List<Appointment> getAppointments() {
		return appointments;
	}

	public void setAppointments(List<Appointment> appointments) {
		this.appointments = appointments;
	}

	public List<ServiceDetails> getServiceDetailsList() {
		return serviceDetailsList;
	}

	public void setServiceDetailsList(List<ServiceDetails> serviceDetailsList) {
		this.serviceDetailsList = serviceDetailsList;
	}

    
    
}
